<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Address' => 'Адрес',
  'City' => 'Город',
  'Client' => 'Клиент',
  'Client Request' => 'Запрос клиента',
  'Clients' => 'Клиенты',
  'Comment Fail' => 'Причина отказа',
  'Comment History' => 'История',
  'Comment Review' => 'Отзыв',
  'Contract Copy' => 'Копия дог.',
  'Cp' => 'КП',
  'Create and exit' => 'Создать и выйти',
  'Create and continue' => 'Создать и продолжить',
  'Create Time' => 'Первый контакт',
  'Create User' => 'Менеджер',
  'Description Production' => 'Описание продукции',
  'Driver' => 'Водитель',
  'Link Type' => 'Вид связи',
  'Manage' => 'Управление',
  'Manager' => 'Менеджер',
  'Company' => 'Организация',
  'Contact' => 'Контактное лицо',
  'Next Time' => 'След. контакт',
  'Phone' => 'Телефон',
  'Photo' => 'Фото',
  'Product' => 'Продукция',
  'Project' => 'Проект',
  'Save and exit' => 'Сохранить и выйти',
  'Save and continue' => 'Сохранить и продолжить',
  'Search' => 'Поиск',
  'Site' => 'Сайт',
  'Sponsor' => 'Поставщик',
  'Status' => 'Статус',
  'TZ' => 'ЧП',
  'Update Time' => 'Посл. контакт',
  'Update User' => 'Изменил',
  'hour' => 'час',
  'Дилер' => '',
  'Рабочий клиент' => '',
  'Сделка заключена и выполнена, переговоры закончились' => '',
);
