<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'AC Amount' => 'Сумма АВ',
  'AC %' => '% АВ',
  'AC Received' => 'Получено АВ',
  'AC Remain Amount' => 'Общий остаток АВ',
  'AC Remain Now' => 'Текущий остаток АВ',
  'Back' => 'Назад',
  'City' => 'Город',
  'Client' => 'Клиент',
  'Comments' => 'Комментарий',
  'Create' => 'Создать',
  'Create Time' => 'Создано',
  'Create User' => 'Менеджер',
  'Manage' => 'Управление',
  'Company' => 'Организация',
  'Contact' => 'Контактное лицо',
  'Project' => 'Проект',
  'Partner' => 'Партнер',
  'Payment' => 'Оплачено',
  'Payment Amount' => 'Сумма сделки',
  'Payment Remain' => 'Остаток',
  'Payments' => 'Оплаты',
  'Reward' => 'Награда',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Update Time' => 'Обновлено',
  'Update User' => 'Обновил',
);
